version: "2"

services:
  web:
    build:
      context: .
      args:
        VERSION: "${VERSION}"
    ports:
      - "80:80"
    depends_on:
     - postgres
    entrypoint: ./wait-for-postgres.sh postgres /app/bin/ib_gib_umb foreground
    volumes:
      - "uploadedfiles:/app/files"

  postgres:
    image: postgres:9.5
    container_name: postgres
    volumes:
      - "./data:/var/lib/postgresql/data"

volumes:
  uploadedfiles:
