version: "2"

services:
  web:
    build:
      context: .
      args:
        VERSION: "${VERSION}"
    ports:
      - "16816:16816"
    expose:
      - 16816
    depends_on:
     - postgres
    entrypoint: ./entrypoint.sh postgres "${PORT}" "${PG_PORT}" "${POSTGRES_USER}" "${POSTGRES_PASSWORD}" /app/bin/ib_gib_umb foreground
    volumes:
      - "uploadedfiles:/app/files"
    restart: always
    networks:
      - front
      - back

  postgres:
    image: postgres:9.5
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    # This mounts the volume on the local machine's file system and not in the
    # container image itself. (The "local machine" may be a vm if using
    # `docker-machine`.)
    volumes:
      - "./postgresqldata:/var/lib/postgresql/data"
    restart: always
    networks:
      - back

  nginx-redirect:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - web
    restart: always
    networks:
      - front

volumes:
  uploadedfiles:

networks:
  front:
  back:
