use Mix.Config

config :web_gib, WebGib.Endpoint,
  https: [port: {:system, "PORT"},
          otp_app: :web_gib,
          keyfile: System.get_env("SSL_KEY_PATH") || "${SSL_KEY_PATH}",
          certfile: System.get_env("SSL_CERT_PATH") || "${SSL_CERT_PATH}"],
  force_ssl: [hsts: false],
  debug_errors: false,
  code_reloader: false,

  url: [host: "www.ibgib.com"],
  # url: [host: "www.ibgib.com", port: {:system, "PORT"}],

  # Path to a manifest containing the digested version of static files. This
  # manifest is generated by the mix phoenix.digest task which you typically
  # run after static files are built.
  cache_static_manifest: "priv/static/manifest.json",


  # For hot code upgrading (?)
  root: ".",

  # Needed to start the server in production
  server: true

# Do not print debug messages in production
config :logger, level: :info

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
