use Mix.Config

config :web_gib, WebGib.Endpoint,
  # only https
  # http: [port: {:system, "PORT"}],
  https: [port: {:system, "PORT"},
          otp_app: :web_gib,
          keyfile: "priv/keys/localhost.key",
          certfile: "priv/keys/localhost.cert"],
  force_ssl: [hsts: true],
  debug_errors: false,
  code_reloader: false,

  url: [host: "ibgib.com", port: {:system, "PORT"}],

  # Path to a manifest containing the digested version of static files. This
  # manifest is generated by the mix phoenix.digest task which you typically
  # run after static files are built.
  cache_static_manifest: "priv/static/manifest.json",


  # For hot code upgrading (?)
  root: ".",

  # Needed to start the server in production
  server: true

# Do not print debug messages in production
config :logger, level: :info

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
